[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci"]
cacheDirectories = ["/root/.npm"]

[phases.build]
cmds = ["npm install && npm run build"]
cacheDirectories = ["/app/.next/cache", "/app/node_modules/.cache"]

[start]
cmd = "npm start"
